COLOR_PRIMARIO = "#161D35"
COLOR_SECUNDARIO = "#F59E0B"
COLOR_VERDE = "#10B981"
COLOR_ROJO = "#EF4444"
COLOR_BLANCO = "#FFFFFF"
COLOR_FONDO = "#F8FAFC"
COLOR_BORDE = "#E2E8F0"
TRANSPARENTE = "transparent"

ALTURA_ESTANDAR_CAMPO = 50
TAMANO_LETRA_NORMAL = 18
TAMANO_LETRA_TITULO = 28